# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - my-bolt-diy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: pnpm install, build, and test
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Copy deploy files
        run: |
          mkdir deploy
          cp -r build/ public/ package.json pnpm-lock.yaml node_modules/ deploy/
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./deploy-artifact

      - name: Unzip artifact into deployment folder
        run: |
          mkdir deploy
          unzip ./deploy-artifact/release.zip -d ./deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0A04E0461BE44F5BDA9C3FDD7158579 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AE34D0FA878F46B2A8B2EBA26DA2F1D0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E65E7B86F5F442CB65E92BD8736561E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-bolt-diy'
          slot-name: 'Production'
          package: ./deploy

          